CREATE TABLE IF NOT EXISTS accounts(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL,
    serverName VARCHAR(5000) NOT NULL,
    apiKey VARCHAR(5000) DEFAULT '',
    userName VARCHAR(5000) DEFAULT '',
    password VARCHAR(5000) DEFAULT '',
    description TEXT DEFAULT '',
    cover BLOB DEFAULT NULL,
    tracker VARCHAR(50) NOT NULL,
    guest TINYINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS filters(
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    title VARCHAR(255) NOT NULL,
    view VARCHAR(50) DEFAULT '',
    status VARCHAR(50) DEFAULT '',
    version VARCHAR(200) DEFAULT '',
    description TEXT
);